### ISSUE TITLE
License UNKNOW even though it's defined in parent pom of dependency

### ISSUE THREAD

**Issue by sslavic** [versioneye/versioneye_sbt_plugin#6]
E.g. "com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.6.3" has a pom without license declared but it's parent pom has license defined and it should be inherited and used as submodule license.

It could be that the actual issue is not in versioneye-sbt-plugin but in sbt, and more specifically in Apache Ivy.

**Comment by reiz** [comment]
@mp911de Can you please take a look to this issue?

**Comment by mp911de** [comment]
Yep. Thanks for the input. Is this issue already solved for the Maven plugin?

**Comment by reiz** [comment]
@mp911de I'm not 100% sure if that works in the VersionEye-Maven-Plugin. The Maven Plugin is using the maven-core project to build up a "Project Model". That Model includes the resolved dependencies and infos from all related files. That's why I would expect that it includes the license from the parent. I will do a test setup for that. 

@sslavic We tested the sbt plugin with some simple sbt files, but not in combination with Ivy. Can you provide one of your projects for testing? We just need the directory structure and the sbt/ivy files. That way we could test the plugin against your setup.

**Comment by mp911de** [comment]
I just checked the license with VersionEye. VersionEye displays the Apache license for `jackson-module-scala_2.10`. I assume this is related to #5 because `"com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.6.3"` currently ends up in artifactId `jackson-module-scala` and not `jackson-module-scala_2.10`.

I'll solve #5 first.

**Comment by reiz** [comment]
@sslavic Can this ticket be close now?

**Comment by sslavic** [comment]
Yep, fixed in 0.1.1
